Mads
audio-engineer/aau-p3-article pull request #164
Opened 2024-12-14 15:59 UTC by MadsHeilmann

2024-12-14 16:51 UTC, Danar435 requested changes

2024-12-14 16:51 UTC, Danar435 commented on src/front-end/data-visualization.tex
I already fixed the images on my PR.

2024-12-14 16:51 UTC, Danar435 commented on src/introduction/index.tex
I can see that you removed the NOVA section. Is this necessary? Also this will likely cause merge conflicts once my PR is merged.

2024-12-14 17:19 UTC, MadsHeilmann commented on src/front-end/data-visualization.tex
Ok- will remove

2024-12-14 17:52 UTC, Danar435 commented on src/main.tex
> +\addbibresource{introduction/index.bib}
Remember to remove this while resolving merge conflicts :)

2024-12-14 17:52 UTC, Danar435 submitted a review, later dismissed

2024-12-14 20:37 UTC, TexWO approved these changes, later dismissed

2024-12-16 11:28 UTC, SebastianMygind approved these changes

2024-12-16 11:39 UTC, Danar435 approved these changes

2024-12-16 11:42 UTC, merged