Fix #144
audio-engineer/aau-p3-article pull request #166
Opened 2024-12-15 19:40 UTC by TexWO

Not sure if we need to explain more in detail for not addressing the loyalty program

2024-12-15 20:22 UTC, SebastianMygind requested changes
Nice, but try to avoid using pronouns

2024-12-15 20:22 UTC, SebastianMygind commented on src/loyalty-program/index.tex
> +As mentioned in the problem statement~\ref{subsec:problem-statement} we wanted to look into the effectiveness
we should not use words such as "we", as it is better to keep it more formal through "the authors" or avoiding making use of pronouns.

2024-12-15 20:22 UTC, SebastianMygind commented on src/loyalty-program/index.tex
> +However, during the project, our focus shifted towards the development of the application and its core features,
try avoiding pronouns, here: "our"

2024-12-15 20:22 UTC, SebastianMygind commented on src/loyalty-program/index.tex
> +As a result, we were unable to further investigate the loyalty program's effectiveness,
avoid using "we"

2024-12-16 18:25 UTC, Danar435 approved these changes

2024-12-16 18:26 UTC, SebastianMygind approved these changes

2024-12-16 18:26 UTC, merged