Resolve #68
audio-engineer/aau-p3-article pull request #69
Opened 2024-10-08 11:09 UTC by MadsHeilmann

2024-10-08 11:15 UTC, SebastianMygind approved these changes

2024-10-08 11:15 UTC, audio-engineer requested changes

2024-10-08 11:15 UTC, audio-engineer commented on src/problem-domain-analysis/classes-objects-and-structure.tex
> +% textidote: ignore begin
You probably want to add `midrule` to the `--remove-macros` arguments in `.textidote` if it complains about incorrect grammar.
And remove the ignores here

2024-10-08 13:01 UTC, TexWO approved these changes

2024-10-16 06:17 UTC, audio-engineer commented
@MadsHeilmann What's the status on this?

2024-10-17 19:20 UTC, MadsHeilmann commented
> @MadsHeilmann What's the status on this?

The issue is with `caption` and it works to ignore the first `midrule` for some reason.
This makes for none of the text being ignored, which is good, but also looks very confusing and ugly, which is bad.

I think for now the bad outweighs the good, so i think it may be best to just delete the branch.

2024-10-18 10:58 UTC, closed without merging